name: firebase_auth_ui_example
description: Demonstrates how to use the firebase_auth_ui plugin.
version: 0.0.1
author: Sandip Soni <sandip.soni0892@gmail.com>
homepage: https://github.com/sam0829/firebase_auth_ui/example

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth_ui:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
